services:
  fluffy:
    image: fluffy
    ports:
      - "5050:80"
    environment:
      - LOCAL_DOCKER=True
      - ASPNETCORE_URLS=http://+:80
    build:
      context: .
      dockerfile: Fluffy/Dockerfile
    depends_on:
      - postgres
    networks:
      - pg_network
  postgres:
    image: postgres:latest
    container_name: fluffy_pg
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    networks:
      - pg_network

networks:
  pg_network:
    driver: bridge

volumes:
  postgres:
