services:
  postgres:
    image: postgres:latest
    container_name: fluffy_pg
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    networks:
      - pg_network

networks:
  pg_network:
    driver: bridge

volumes:
  postgres: